### ISSUE TITLE
When the score of a page doesn't exist, calculate it when a user clicks on the badge

### ISSUE THREAD

**Issue by guillaumew** [cnumr/ecoindex_badge#104]
As a user if a page doesn't have a score yet I can see a badge with question mark in it.
Example here: https://simbios.fr/services/ (scroll at bottom of the page)

If I click on it I expect to be redirected to the eco-index website with at least the URL set in the input. Even better would be that the calculation directly launches on page load.

What I got now is that I'm redirected to eco-index main page.

**Comment by vvatelot** [comment]
**🙏🏻 Praise:** Thank you for your contribution! I think this needs a more detailed user scenario:
- What happens exactly on click of the badge? (open a popin/popup..?)
-

**Comment by guillaumew** [comment]
If a page doesn't have a score, if a user clicks on the badge:
- then it opens the eco-index website 
- target is set according to the way it is implemented (new tab with the code provided in readme)
- when the ecoindex website opens, the requested URL is already set in the input and it launches the test
- Therefore I can the the popin with the text: "L’analyse est en cours pour « https://xxx »"
- If I wait a minute I can see the score
- When the initial page is reloaded, the score is displayed

OR

If a page doesn't have a score, if a user clicks on the badge:
- then it opens the eco-index website 
- target is set according to the way it is implemented (new tab with the code provided in readme)
- when the ecoindex website opens, the requested URL is already set in the input
- a message reads: "This page doesn't have a score yet. Click on 'Tester le site' in order to get its environmental footprint." (to be adapted) The message can be displayed in a Toast or Snackbar in order to understand that it is contextual.

Both scenarios are fine to me.

**Comment by guillaumew** [comment]
I just realized this issue might be more about [ecoindex_bff](https://github.com/cnumr/ecoindex_bff)

**Comment by vvatelot** [comment]
Hello @guillaumew IMO, this is a issue about the plugin itself and not the BFF. The main question that we need to answer to is "what do we want to do with this badge?"...

The first idea was to keep it the smallest and simpliest as possible... But if we think it could be interesting to make it evolve, let's do it...
