### ISSUE TITLE
Quand on clic sur le badge, on ne tombe pas sur le bon rapport

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_badge#11]
Je viens de faire une modification sur mon site 
![image](https://user-images.githubusercontent.com/24810599/226166357-1467cff0-689f-4ec8-8cee-0e0828492b5a.png)
le badge est cohérent par rapport à mes actions et à [mon dernier rapport](https://www.ecoindex.fr/resultat/?id=db1edf16-9b04-4c63-a2d7-fb0a83fd6f15).

Je clic sur le lien (donc en lançant l'url https://bff.ecoindex.fr/redirect/?url=https://novagaia.fr/)

Je tombe sur [un ancien rapport](https://www.ecoindex.fr/resultat/?id=14fa38d1-d32d-4820-b8d3-d357dc374acd) (fait plus tôt dans la journée).
![image](https://user-images.githubusercontent.com/24810599/226166438-d24c1d65-c8aa-49ec-a8b3-b990fadd80c0.png)

Pareil dans le plugin chrome
![image](https://user-images.githubusercontent.com/24810599/226166512-3f8b07ad-d725-419f-965c-3c59cc43d0c9.png)

**Comment by hrenaud** [comment]
Merde, j'ai reculé, c'est bizarre, j'ai enlevé le chargement d'une police pour obtenir ce résultat. Je ne comprends pas comment j'ai pu atteindre un B, puis redescendre à C en faisant cette action en plus 🤷‍♂️

**Comment by jpkha** [comment]
Je ne crois pas qu'il soit possible d'invalider un cache client à moins que ça soit l'utilisateur qui vide son cache côté navigateur. Tant que le cache est actif, le navigateur ne fera pas de requête au serveur.

**Comment by vvatelot** [comment]
@hrenaud du coup cette issue est elle encore utile ?

**Comment by pickbeam-webmarketing** [comment]
Je crois pas qu'on puisse dire à tous les visiteurs de faire `ctrl+maj+R` :) ?

**Comment by jpkha** [comment]
Je crois pas qu'on puisse dire à tous les visiteurs de faire ctrl+maj+R :) ?

**Comment by hrenaud** [comment]
je suis d'accord avec @jpkha et en plus, je crois l'avoir fait (j'ai récupéré mon B, donc je peux plus tester)

**Comment by vvatelot** [comment]
Pfff... Si les gens y mettent pas du leur aussi ! :sweat_smile:
