### ISSUE TITLE
Obligation d'avoir un trailing slash

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_badge#16]
Context
Sur un WordPress hébergé par Infomaniak, je n'ai pas la main sur la conf. serveur. La conf. est possible dans WordPress pour forcer l'ajout du trailing slash, mais pas par défaut et pas à la porté de "Madame et monsieur tout le monde".

Le javascript ne détecte pas ce manque, donc envoie domain.td et non pas domain.td/ hors l'API nécessite visiblement ce trailing slash. Il faut homogénéiser et sécuriser les conf sans ce trailing slash 
- Soit ne pas le rendre obligatoire sur l'API
- Soit agir pour que le javascript le détecte et l'ajoute si besoin.

**Comment by vvatelot** [comment]
Corrigé par https://github.com/cnumr/ecoindex_bff/pull/28
