### ISSUE TITLE
Refactoring code between light and dark version

### ISSUE THREAD

**Issue by JulienWilhelm** [cnumr/ecoindex_badge#5]
There are currently 2 _almost identical_ JS files to handling light and dark mode. 
Only one should be used to make maintenability easier.

**Comment by vvatelot** [comment]
Yep, I was thinking about this... How could we do that ? Is there a way to pass a query argument to a javascript file ?

**Comment by vvatelot** [comment]
@JulienWilhelm what do you think about this implementation ? :thinking:
