### ISSUE TITLE
Use local storage to limit server calls

### ISSUE THREAD

**Issue by JulienWilhelm** [cnumr/ecoindex_badge#6]
Each time a user refreshes a page where the logo is embedded with JavaScript, the API is called. This behavior will consume bandwidth and might create performance issues on both sides (website and API).

It should be possible to use local storage to avoid this.

**Comment by vvatelot** [comment]
Hello @JulienWilhelm, sorry did not receive a notification on your issue :sweat_smile: 
What do you have in mind for localstorage here ?

I already apply a cache on the badge coming from the BFF:
```
Cache-Control: max-age=604800, public
Vary: Origin,X-Ecoindex-Url,X-Ecoindex-Theme
X-Ecoindex-Theme: light
X-Ecoindex-Url: https://www.ecoindex.fr
```

Isn't it enough ? :thinking:

**Comment by JulienWilhelm** [comment]
I missed it! Sorry. 

Maybe you should specified in README that the result will not updated for 7 days.

**Comment by jpkha** [comment]
Should we limit the cache to 24 hours like the Ecoindex extension?
