### ISSUE TITLE
Petits retours

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_badge#9]
# Plus d'explications quand la page n'a pas été testée
Quand la page n'a pas été testée, le badge affiche un `?`, ce serait bien d'expliquer ce que cela signifie au roll over ou au touch ou même remplacer ce `?` par un message explicite.

# Refresh
J'ai mon badge sur une page en `?`, je lance le test. Quand il est terminé, je refresh ma page, le badge est toujours en `?` c'est normal ou c'est un bug dans mon implémentation (https://github.com/NovaGaia/gatsby-plugin-ecoindexbadge-v2)

# data-theme
Mon framework css (DaisyUI/Tailwindcss) utilise déjà `data-theme`, ça entre donc en conflit et mets un background au bouton. Peut-être qu'un `data-*` moins générique serait meilleur 🤷‍♂️

**Comment by jpkha** [comment]
Je pense aussi qu'on devrait changer la variable sachant qu'en plus Tailwind est une lib très utilisé et donc potentiellement plusieurs utilisateurs pourraient avoir le souci.

Pourquoi `data-*` on pourrait directement utiliser un nom comme : `ecoindex-theme` non ?
Au pire `data-ecoindex-theme` ?

**Comment by hrenaud** [comment]
@vvatelot et @jpkha j'ai fait une MR #14 ou je casse tout :)

J'ai, entre autres, mis `data-ecoindex-theme`

**Comment by vvatelot** [comment]
Oui, dans tous les cas, vu les changements, c'est prévu de faire une release majeure pour ça ?
